# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            mpolednik.github.io
tagline:          'virtualization & tech blog'
description:      'A software engineer contributing to oVirt project...'
url:              http://mpolednik.github.io

author:
  name:           'Martin Polednik'
  url:            http://mpolednik.github.io

paginate:         5

# Custom vars
version:          1.0.0

gems: [
    jekyll-paginate
]
