# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            mpolednik.github.io
tagline:          'virtualization & tech blog'
description:      'A software engineer and virtualization enthusiast working on oVirt project.'
url:              https://mpolednik.github.io
excerpt_separator: '<!--more-->'

author:
  name:           'Martin Polednik'
  url:            https://mpolednik.github.io

paginate:         5

# Custom vars
version:          1.0.0

plugins:
    - jekyll-paginate
